Vagrant.configure("2") do |config|
  config.vm.box = "chef/ubuntu-14.04"
  config.vm.synced_folder "../build/libs", "/target", create: true
  config.vm.synced_folder "log", "/log", create: true
  config.vm.network "forwarded_port", guest: 8080, host: 8090

  config.vm.provision "docker" do |d|
    d.build_image "--tag=bookapp /vagrant"
    d.run "bookapp",
      args: "-p 8080:8080 -v /target:/target -v /log:/log"
  end

end